### ISSUE TITLE
По неделе 3

### ISSUE THREAD

**Issue by alekseik1** [barklan/mipt_adv_py#1]
## Необязательные замечания:
1. `if (fl[-3:] == ".py"):` -- расширение можно проверять еще через Pathlib: [вот так](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.suffix).
2. Консистентность кавычек -- если ты начал использовать одинарные кавычки, то используй их везде в коде. Если начал использовать двойные кавычки, то используй только их. Как я понял, ты используешь двойные, но местами встречаются и одинарные (например, `with zipfile.ZipFile("main.zip", 'r') as zip_ref:`)
3. Данные из `json.loads()` не обязательно копировать (вызывать `.copy()`) - `dict` не привязывается к файлу. Как я понимаю, ты хотел держать отобразить содержимое до и после, так что все ок.
4. По PEP8:
- есть длинные строки (например, `df_out = pd.DataFrame(np.insert(df.values, int(len(df)/2), values=[-200, -200, -200, -200], axis=0))`), которые желательно разбивать на две;
- есть замечания по лишним пробелам - их можно увидеть через flake8 (см. ниже)

#### flake8
Если пользуешься Anaconda/Miniconda:
```bash
conda install flake8
```

Если пользуешься `pip`:
```bash
pip install flake8
```

После этого сконвертируй ноутбук в .py файл и запусти `flake8 <путь до файла>`. У меня было `flake8 3w.py`.
У flake8 есть куча настроек, подробности можно нагуглить. Мы будем потихоньку привыкать к PEP8, поэтому лучше сейчас поставить flake8 и начать проверять свой код.

По итогу: работа проделана отлично. 
Мне понравилось, что ты разобрался с другими библиотеками, о которых я не упоминал (`pandas`, `numpy`, `zipfile`).

**Comment by barklan** [comment]
Исправлено
